services:
  - type: web
    name: nekoz-mindmatch-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start -w server
    envVars:
      - key: CORS_ORIGIN
        sync: false
